import { minify as htmlMinifier } from 'html-minifier-terser'

/**Minify a piece of code 
 * @param someCode throw any html, css or javascript code here, just make sure you don't put anything cursed
 * @returns minfied code
 */
export function minify(someCode: string) {
  return htmlMinifier(someCode.trim(), {
    minifyCSS: true,
    minifyJS: true,
    collapseBooleanAttributes: true,
    includeAutoGeneratedTags: true,
    collapseWhitespace: true,
    decodeEntities: true,
    html5: true
  })
}